language: node_js
branches:
  only:
    - master
cache: 
  yarn: true
node_js:
  - 12
sudo: false
script:
  - yarn run test:ci && yarn run build
after_success:
  - yarn run coveralls
  - yarn run deploy
